name: landscape-booth
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib-base
  - opencv
  - ipywidgets
  - ipywebrtc
  - ipycanvas
  - jupyterlab=3
  - fastscapelib-f2py
  - pooch
  - voila
  - scikit-image
